module.exports = {
	SEARCH_CITY: 'SEARCH_CITY',
	SEARCH_ARTIST: 'SEARCH_ARTIST',
	RECEIVE_RESULTS: 'RECEIVE_RESULTS',
	RECEIVE_ARTIST_RESULTS: 'RECEIVE_ARTIST_RESULTS',
	SEARCH_ID: 'SEARCH_ID',
	SEARCH_ARTIST_ID: 'SEARCH_ARTIST_ID',
	RECEIVE_CALENDARS: 'RECEIVE_CALENDARS',
	RECEIVE_RESULTS_PAGE:'RECEIVE_RESULTS_PAGE',
	RECEIVE_AREA_ID: 'RECEIVE_AREA_ID',
	RECEIVE_PAGE: 'RECEIVE_PAGE',
	RECEIVE_ARTIST_CALENDARS: 'RECEIVE_ARTIST_CALENDARS',
	SAVE_CONCERT_TO_CALENDAR: 'SAVE_CONCERT_TO_CALENDAR',
	RECEIVE_CONCERTS: 'RECEIVE_CONCERTS',
	REMOVE_CONCERT: 'REMOVE_CONCERT',
	SAVE_CONCERT_TO_VAULT: 'SAVE_CONCERT_TO_VAULT',
	RECEIVE_VAULT_CONCERTS: 'RECEIVE_VAULT_CONCERTS',
	REMOVE_VAULT_CONCERT: 'REMOVE_VAULT_CONCERT'
}