module.exports = {
	SEARCH_CITY: 'SEARCH_CITY',
	SEARCH_ARTIST: 'SEARCH_ARTIST',
	RECEIVE_RESULTS: 'RECEIVE_RESULTS',
	RECEIVE_ARTIST_RESULTS: 'RECEIVE_ARTIST_RESULTS',
	SEARCH_ID: 'SEARCH_ID',
	SEARCH_ARTIST_ID: 'SEARCH_ARTIST_ID',
	RECEIVE_CALENDARS: 'RECEIVE_CALENDARS',
	RECEIVE_ARTIST_CALENDARS: 'RECEIVE_ARTIST_CALENDARS',
	SAVE_CONCERT_TO_CALENDAR: 'SAVE_CONCERT_TO_CALENDAR'

}